services:
  app:
    build: .
    container_name: whatsapp_bot_python
    command: python src/app.py
    ports: 
      - 8080:8080
    volumes:
      - .:/whatsapp_bot_python
  
#conda environment
conda:
  name: conda_env
  channels:
    - conda-forge
  dependencies:
    - python=3.13
    - flask    